export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST"
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS"

export const DELETE_POST_REQUEST = 'DELETE_POSTS_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POSTS_SUCCESS'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'


export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'

export const COMMENT_POST_REQUEST = 'COMMENT_POST_REQUEST'
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS'